In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [10]:
A = np.random.randn(10)
A

array([ 1.90239119,  0.70866891,  0.52460413,  0.55533045,  0.86010709,
        1.35279353,  0.29824187,  1.32488658, -0.24149802, -1.69292952])

In [11]:
B = np.random.randn(10)
B

array([ 0.7404449 ,  0.15169562,  0.34129094,  0.77898936, -2.10016103,
       -0.01827342,  0.05236886, -0.30419837, -0.47599299,  1.34036304])

In [12]:
# binary functions
np.add(A,B)

array([ 2.64283609,  0.86036452,  0.86589507,  1.33431981, -1.24005395,
        1.33452011,  0.35061073,  1.02068821, -0.71749101, -0.35256648])

In [13]:
np.maximum(A,B)

array([ 1.90239119,  0.70866891,  0.52460413,  0.77898936,  0.86010709,
        1.35279353,  0.29824187,  1.32488658, -0.24149802,  1.34036304])

In [14]:
np.minimum(A,B)

array([ 0.7404449 ,  0.15169562,  0.34129094,  0.55533045, -2.10016103,
       -0.01827342,  0.05236886, -0.30419837, -0.47599299, -1.69292952])