In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=0)

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1,ser2],axis=0)

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2],axis=0,keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2],axis=0,keys=['cat1','cat2']).unstack()

T    U    V    X    Y
cat1  0.0  1.0  2.0  NaN  NaN
cat2  NaN  NaN  NaN  3.0  4.0

In [14]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [16]:
dframe1

X         Y         Z
0 -0.660772  0.461477  0.264942
1  0.098244 -1.399829  1.063088
2 -0.393547  1.212254  0.639030
3 -1.113458  0.559680 -0.909835

In [17]:
dframe2

Y         Q         X
0  0.086980  0.998207  1.170845
1 -1.072105 -0.336415 -0.152744
2 -0.917705 -0.146996  0.306220

In [21]:
pd.concat([dframe1,dframe2], axis=0)

Q         X         Y         Z
0       NaN -0.660772  0.461477  0.264942
1       NaN  0.098244 -1.399829  1.063088
2       NaN -0.393547  1.212254  0.639030
3       NaN -1.113458  0.559680 -0.909835
0  0.998207  1.170845  0.086980       NaN
1 -0.336415 -0.152744 -1.072105       NaN
2 -0.146996  0.306220 -0.917705       NaN

In [20]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.307926  0.062717  0.312697
1       NaN  0.565910 -0.315369  1.184843
2       NaN -0.060537 -1.956943  1.416270
3       NaN  0.141533 -0.487406  0.488885
0 -1.376871  0.023645  1.875649       NaN
1 -0.528523 -2.215796 -0.462958       NaN
2 -0.295373  0.422896  0.114432       NaN

In [21]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.307926  0.062717  0.312697
1       NaN  0.565910 -0.315369  1.184843
2       NaN -0.060537 -1.956943  1.416270
3       NaN  0.141533 -0.487406  0.488885
4 -1.376871  0.023645  1.875649       NaN
5 -0.528523 -2.215796 -0.462958       NaN
6 -0.295373  0.422896  0.114432       NaN