In [1]:
import numpy as np

In [45]:
my_list1 = [1, 2, 3, 4]

In [46]:
my_array1 = np.array(my_list1)

In [47]:
my_array1

array([1, 2, 3, 4])

In [59]:
my_list2 = [11, 22, 33, 44]

In [60]:
my_lists = [my_list1, my_list2]

In [61]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [62]:
my_array2 = np.array(my_lists)

In [63]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [64]:
my_array2.shape

(2, 4)

In [38]:
my_array2.dtype

dtype('int64')

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
my_zeros_array = np.zeros(5)

In [67]:
my_zeros_array.dtype

dtype('float64')

In [68]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [69]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [72]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])