In [1]:
import numpy as np

In [5]:
arr = np.arange(10, 21)

In [6]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[8]

18

In [9]:
arr[1:5]

array([11, 12, 13, 14])

In [10]:
arr[0:5]

array([10, 11, 12, 13, 14])

In [11]:
arr[:5]

array([10, 11, 12, 13, 14])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [14]:
arr = np.arange(10,21)

In [15]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr

array([10, 11, 12, 13, 14, 15])

In [18]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [20]:
arr_copy = arr.copy()

In [22]:
arr_copy


array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [23]:
arr_2d = np.array(([5, 10, 15], [20,25,30], [35,40,45]))

In [26]:
arr_2d.shape

(3, 3)

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[2][2]

45

In [42]:
arr_2d[2][2]

45

In [51]:
arr_2d[:,2]

array([15, 30, 45])

In [23]:
arr_2d[1][0]

20

In [49]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [52]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [53]:
arr_2d[:,1]

array([10, 25, 40])

In [54]:
arr_2d[2]

array([35, 40, 45])

In [27]:
arr_2d[:,2]

array([15, 30, 45])

In [66]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr_length = arr2d.shape[1]

In [30]:
arr_length


10

In [31]:
for i in range(arr_length):
    arr2d[i] = i

In [32]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [33]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [34]:
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [35]:
arr2d[[2,4][0]]

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])